### ISSUE TITLE
Postload for event source

### ISSUE THREAD

**Issue by leo880418** [nexuni/Famcy#37]
Situation

self.card_2.layout.content[0][0].layout.content[0][0].update({"data": Famcy.FManager['error_log']})
Before Update the table 4 row of data
After Update the table  6 row of data
I have a function which will change the color of the table. I should loop through 6 row of data. However, the data not yet update, so there will be only 4 rows. This will cause [i] list index out of range.
Add postload for evernt source might help this question.

**Comment by w20010703** [comment]
update version 3.51
